apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: spring-petclinic
  name: alb-role
rules:
  - apiGroups:
      - ""
      - extensions
    resources:
      - configmaps
      - endpoints
      - events
      - ingresses
      - ingresses/status
      - services
      - pods/status
    verbs:
      - create
      - get
      - list
      - update
      - watch
      - patch
  - apiGroups:
      - ""
      - extensions
    resources:
      - nodes
      - pods
      - secrets
      - services
      - namespaces
    verbs:
      - get
      - list
      - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: alb-ingress-controller
  name: alb-serviceaccount
  namespace: spring-petclinic
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: alb-role-binding
  namespace: spring-petclinic
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: alb-role
subjects:
  - kind: ServiceAccount
    name: alb-serviceaccount
    namespace: spring-petclinic