apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-binding
  namespace: spring-petclinic
subjects:
- kind: ServiceAccount
  name: default
  namespace: spring-petclinic
roleRef:
  kind: Role
  name: namespace-reader
  apiGroup: rbac.authorization.k8s.io
