apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-server
  namespace: spring-petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-server
  template:
    metadata:
      labels:
        app: admin-server
    spec:
      containers:
        - name: admin-container
          image: public.ecr.aws/y6x2k4a9/spring-petclinic-admin-server:latest
          imagePullPolicy: Always
          resources:
                  limits:
                    cpu: 1
                    memory: 1Gi
                  requests:
                    cpu: 100m
                    memory: 250Mi
          volumeMounts:  
            - name: petclinic-volume
              mountPath: /data  # Chemin de montage dans le conteneur
          ports:
            - containerPort: 9090
      imagePullSecrets:
        - name: my-dockerhub-secret
      volumes:  
        - name: petclinic-volume
          persistentVolumeClaim:
            claimName: petclinic-pvc
      restartPolicy: Always
---
#Le service ClusterIP est le type par défaut au sein de Kubernetes
#Il reçoit une adresse IP interne au cluster, ce qui rend ses Pods uniquement accessibles depuis le cluster
#Ce service doit juste est accessible par l'API
apiVersion: v1
kind: Service
metadata:
  labels:
    app: admin-server
  name: admin-service
  namespace: spring-petclinic
spec:
  type: ClusterIP
  ports:
  - name: "http"
    port: 9090
    targetPort: 9090
    protocol: TCP
  selector:
    app: admin-server
