apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-server
  namespace: spring-petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-server
  template:
    metadata:
      labels:
        app: admin-server
    spec:
      containers:
        - name: admin-container
          image: public.ecr.aws/y6x2k4a9/spring-petclinic-admin-server:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 250Mi
          ports:
            - containerPort: 9090
      imagePullSecrets:
        - name: my-dockerhub-secret
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: admin-server
  name: admin-service
  namespace: spring-petclinic
spec:
  type: ClusterIP
  ports:
    - name: "http"
      port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
    app: admin-server
