apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers-service
  namespace: spring-petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customers-service
  template:
    metadata:
      labels:
        app: customers-service
    spec:
      containers:
        - name: customers-container
          image: public.ecr.aws/y6x2k4a9/spring-petclinic-customers-service:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: 2000m
              memory: 1Gi
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: my-dockerhub-secret
      restartPolicy: Always
---
#Le service ClusterIP est le type par défaut au sein de Kubernetes
#Il reçoit une adresse IP interne au cluster, ce qui rend ses Pods uniquement accessibles depuis le cluster
#Ce service doit juste est accessible par l'API
apiVersion: v1
kind: Service
metadata:
  name: customers-service
  namespace: spring-petclinic
spec:
  ports:
  - name: "http"
    port: 80
    targetPort: 8080
  selector:
    app: customers-service
  status:
  loadBalancer: {}
