apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
  namespace: spring-petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
      - name: discovery-container
        image: public.ecr.aws/y6x2k4a9/spring-petclinic-discovery-server:latest
        imagePullPolicy: Always
          resources:
                  limits:
                    cpu: 1
                    memory: 1Gi
                  requests:
                    cpu: 100m
                  memory: 250Mi
          volumeMounts:  
            - name: petclinic-volume
              mountPath: /app/data/  # Chemin de montage dans le conteneur
          ports:
            - containerPort: 8761
      imagePullSecrets:
        - name: my-dockerhub-secret
        volumes:  
        - name: petclinic-volume
          persistentVolumeClaim:
            claimName: petclinic-pvc
        restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: discovery-server
  name: discovery-service
  namespace: spring-petclinic
spec:
  type: ClusterIP
  ports:
    - name: "http"
      port: 8761
      targetPort: 8761
      protocol: TCP
  selector:
    app: discovery-server
