name: Apply Terraform 
run-name: Starting to apply terraform
on: 
  push:
    branches:
      - "main"

jobs:
  create-vpc:
    runs-on: ubuntu-22.04
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: eu-west-3
      TF_VAR_DB_USERNAME:  ${{ secrets.DB_USERNAME }}
      TF_VAR_DB_PASSWORD:  ${{ secrets.DB_PASSWORD }}
      TF_VAR_GRAFANA_PASSWORD:  ${{ secrets.GRAFANA_PASSWORD }}
    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.5"
          terraform_wrapper: false

      - name: Terraform Init
        id: init
        run: |
          cd terraform-projet-petclinic
          terraform init
      
      - name: Terraform Apply to Create VPC
        id: apply-vpc
        run: |
          cd terraform-projet-petclinic
          terraform apply -auto-approve -target=aws_vpc.main

      - name: Get VPC ID from Terraform Output
        id: get-vpc-id
        run: |
          cd terraform-projet-petclinic
          vpc_id=$(terraform output -raw vpc_id)
          echo "VPC_ID=${vpc_id}" >> $GITHUB_ENV
    outputs:
      VPC_ID: ${{ steps.get-vpc-id.outputs.VPC_ID }}

  use-vpc:
    runs-on: ubuntu-22.04
    needs: create-vpc
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: eu-west-3
      TF_VAR_DB_USERNAME:  ${{ secrets.DB_USERNAME }}
      TF_VAR_DB_PASSWORD:  ${{ secrets.DB_PASSWORD }}
      TF_VAR_GRAFANA_PASSWORD:  ${{ secrets.GRAFANA_PASSWORD }}
      TF_VAR_vpc_id: ${{ needs.create-vpc.outputs.VPC_ID }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.5"
          terraform_wrapper: false
      
      - name: Terraform Init
        id: init
        run: |
          cd terraform-projet-petclinic
          terraform init
      
      - name: Terraform Validate
        id: validate
        run: |
          cd terraform-projet-petclinic
          terraform validate -no-color
      
      - name: Terraform Plan
        id: plan
        run: |
          cd terraform-projet-petclinic
          terraform plan -no-color  -detailed-exitcode
        continue-on-error: true
        
      - name: Terraform Apply
        id: apply
        run: |
          cd terraform-projet-petclinic
          terraform apply -auto-approve
