name: Apply Terraform

on:
  push:
    branches:
      - "main"

jobs:
  create-vpc:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: eu-west-3
      TF_VAR_DB_USERNAME: ${{ secrets.DB_USERNAME }}
      TF_VAR_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      TF_VAR_GRAFANA_PASSWORD: ${{ secrets.GRAFANA_PASSWORD }}

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.5"
          terraform_wrapper: false

      - name: Terraform Init
        id: init
        run: |
          cd terraform-projet-petclinic
          terraform init -upgrade

      - name: Terraform Apply to Create VPC
        id: apply-vpc
        run: |
          cd terraform-projet-petclinic
          terraform apply -auto-approve -target=aws_vpc.petclinic_vpc

      - name: Get VPC ID from Terraform Output
        id: get-vpc-id
        run: |
          cd terraform-projet-petclinic
          vpc_id=$(terraform output -raw vpc_id)
          echo "::set-output name=VPC_ID::$vpc_id"

  use-vpc:
    runs-on: ubuntu-latest
    needs: create-vpc
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: eu-west-3
      TF_VAR_DB_USERNAME: ${{ secrets.DB_USERNAME }}
      TF_VAR_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      TF_VAR_GRAFANA_PASSWORD: ${{ secrets.GRAFANA_PASSWORD }}
      TF_VAR_vpc_id: ${{ needs.create-vpc.outputs.VPC_ID }}

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.5"
          terraform_wrapper: false

      - name: Terraform Init
        id: init
        run: |
          cd terraform-projet-petclinic
          terraform init -upgrade

      - name: Terraform Validate
        id: validate
        run: |
          cd terraform-projet-petclinic
          terraform validate -no-color

      - name: Terraform Apply with VPC ID
        id: apply
        run: |
          cd terraform-projet-petclinic
          terraform apply -auto-approve
